# Generated by Django 4.2.2 on 2023-06-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('work_experience', models.PositiveIntegerField()),
                ('current_police_check', models.BooleanField(default=False)),
                ('children_check', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=60)),
                ('cv', models.FileField(upload_to='')),
                ('qualification_pdf', models.FileField(upload_to='')),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.position')),
                ('qualification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.qualification')),
            ],
        ),
    ]
