# Generated by Django 4.2.2 on 2023-06-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='cv',
            field=models.FileField(upload_to='cv_pdf'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='qualification_pdf',
            field=models.FileField(upload_to='qualification_pdf'),
        ),
    ]
