# Generated by Django 4.2.2 on 2023-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_jobseeker_cv_alter_jobseeker_qualification_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
